#!/bin/bash
#export ECHO_ON=1
[[ $ECHO_ON = "1" ]] && echo Starting ~/.bashrc

export SCRIPTS_PATH=~/scripts

for script in common python vw; do
    [[ $ECHO_ON = "1" ]] && echo Loading $SCRIPTS_PATH/bash/${script}.sh
    source $SCRIPTS_PATH/bash/${script}.sh
done

if [ $PLATFORM = "Darwin" ]; then
    [[ $ECHO_ON = "1" ]] && echo Loading $SCRIPTS_PATH/bash/macos.sh
    source $SCRIPTS_PATH/bash/macos.sh
elif [ $PLATFORM = "Linux" ]; then
    [[ $ECHO_ON = "1" ]] && echo Loading $SCRIPTS_PATH/bash/linux.sh
    source $SCRIPTS_PATH/bash/linux.sh
fi

for rc in .atlrc .privaterc; do
    if [ -e ~/$rc ]; then
        [[ $ECHO_ON = "1" ]] && echo Loading $rc
        source ~/$rc
    fi
done

[[ $ECHO_ON = "1" ]] && echo .bashrc loaded
